# Generated by Django 5.2.3 on 2025-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Do zrobienia'), ('in_progress', 'W trakcie'), ('done', 'Zakończone')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
